### ISSUE TITLE
sql statement not valid with mysql

### ISSUE THREAD

**Issue by skiane** [snewscms/snews1.80#2]
Default snews sql engine is now sqlite (1.80), however it should still be compatible with mysql.

In function `update_articles()`, the following statement is not valid with mysql

```
UPDATE articles 
            SET published = 1 
            WHERE published = 2 AND date <= datetime($now)
```

Specifically, the `date time` function does not exists.

**Comment by ebookcms** [comment]
Thank Skiane.

Issue fixed.
I'm sorry my mistake, when I made everything to work for sqlite-database,  I forget to test update_articles with mysql.

With your help, we make this better, thanks

Best reagards,
Rui Mendes

**Comment by snewscms** [comment]
Thank you Skiane.

Issue fixed.

I'm sorry my mistake, when I made everything to work for sqlite-database, I forget to test update_articles with mysql.

With your help, we make this better, thanks

Best reagards,
Rui Mendes
