### ISSUE TITLE
Editing Existing Article Changes Title to SEFTitle

### ISSUE THREAD

**Issue by RobsWebsites** [snewscms/snews1.80#4]
I've upgraded from an existing 1.7 installation to 1.8.
Currently using SQLite (after converting the MySQL database).
When I edit an existing article the 'Title' in the form changes to seftitle.
So, for instance, a title of 'This Is A New Article' displays in the form title box as 'this-is-a-new-article'.
I've installed the latest version today (29 May, 16) and the problem is still there.

**Comment by skiane** [comment]
confirmed !
I've provided a correction (see pull requests)
In the mean time, you can use this version https://github.com/skiane/snews1.80/blob/master/admin.php

**Comment by RobsWebsites** [comment]
Thanks, confirmed fixed.
