### ISSUE TITLE
Discussion: should we switch to filter_imput

### ISSUE THREAD

**Issue by skiane** [snewscms/snews1.80#8]
nowadays (since php5.2), [filter_input](http://php.net/manual/en/function.filter-input.php) is the recommended method to access `$_GET`, `$_POST`, `$_SESSION`...

Would you accept pull requests to migrate the code to use this method (which will be safer, and will improve code quality) ?

**Comment by snewscms** [comment]
Yes Skiane I accept, my personal projects I use it.

We can rewrite XSS attacks, snews has a confused and long functions. I think we can fight with better code and small

**Comment by snewscms** [comment]
After almost 2 weeks with exhausted tests cleanXSS was changed for better.
filter_input and filter_var will be WIP (Work in progress)
